#!/bin/sh

# Update these when the Scala or Escalator version changes:
LIB1=target/scala_2.8.0
LIB2=lib_managed/scala_2.8.0/compile
LIB3=project/boot/scala-2.8.0/lib
ZIPNAME=Escalator_2.0.RC7.zip

mkdir staging
mkdir staging/lib
cp distrib/* staging
cp LICENSE NOTICE staging
cp $LIB1/escalator*.jar staging/lib/escalator.jar
cp $LIB2/js*.jar staging/lib/js.jar
cp $LIB3/scala-compiler.jar staging/lib
cp $LIB3/scala-library.jar staging/lib
cp $LIB2/scala-swing*.jar staging/lib/scala-swing.jar
cp $LIB2/scalacheck*.jar staging/lib/scalacheck.jar
cp $LIB2/specs*.jar staging/lib/specs.jar
rm -f $ZIPNAME
cd staging
zip -r ../$ZIPNAME *
cd ..
rm -rf staging
