#!/bin/sh
ESCHOME=`dirname $0`
java -cp $ESCHOME/escalator_2.8.0-2.0.jar:$ESCHOME/js-1.7R2.jar:$ESCHOME/scala-compiler.jar:$ESCHOME/scala-library.jar:$ESCHOME/scala-swing-2.8.0.jar:$ESCHOME/scalacheck_2.8.0-1.7.jar:$ESCHOME/specs_2.8.0-1.6.5.jar:$ESCHOME/jlfgr-1_0.jar:$ESCHOME/test-interface-0.3.jar:$ESCHOME edu.depauw.escalator.Main $*
